### ISSUE TITLE
Unable to refresh the gateways list without sudo

### ISSUE THREAD

**Issue by ghost** [linuxmint/pia-manager#11]
By running the pia-manager (version 1.0.8) in the terminal, when clicking the refresh button for the gateways list, some errors are printed in the terminal:

`chingyinwan123@chingyinwan123-UX410UAK:~$ pia-manager`
The refresh button is clicked:
`Traceback (most recent call last):`
`  File "/usr/lib/pia-manager/pia-manager.py", line 125, in on_button_refresh_clicked`
`    self.download_latest_gateways()`
`  File "/usr/lib/pia-manager/pia-manager.py", line 196, in download_latest_gateways`
`    with open('/usr/share/pia-manager/gateways.list.dynamic', 'w') as fp:`
`PermissionError: [Errno 13] Permission denied: '/usr/share/pia-manager/gateways.list.dynamic'`

If pia-manager is run with sudo, no errors are printed when the refresh button is clicked.

**Comment by clefebvre** [comment]
@chingyinwan123 ah.. that's a remnant of when PIA Manager was running as root.

We could save the file in ~/.config/pia-manager/gateways.list.dynamic, and at startup load either that file or /usr/share/pia-manager/gateways.list.dynamic, depending on which of the two is the more recent.
